# Generated by Django 2.2.7 on 2020-08-27 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200630_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Compañia'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Role'},
        ),
    ]
