# Generated by Django 2.2.7 on 2020-09-11 03:42

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200826_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_email',
            field=models.CharField(max_length=40, verbose_name='Email de contacto'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_name',
            field=models.CharField(max_length=30, verbose_name='Nombre de Contacto'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(max_length=30, verbose_name='Celular de Contacto'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Actividad Económíca'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to=account.models.user_directory_path, verbose_name='Logo de la Compañia'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre de Compañia'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.CharField(max_length=9, verbose_name='N.I.T.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Company', verbose_name='Compañia'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Número Celular'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Rol', verbose_name='Rol de Usuario'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='code',
            field=models.IntegerField(verbose_name='Código de Rol'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre del Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_id',
            field=models.CharField(max_length=15, verbose_name='Docuemnto de Identidad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.CharField(max_length=2, verbose_name='Tipo de Documento'),
        ),
    ]
