# Generated by Django 2.2.7 on 2020-07-15 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticulosDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_articulo', models.IntegerField()),
                ('nom_articulo', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=12)),
                ('unidad_venta', models.IntegerField()),
                ('factor_estiba', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('inventario_seguridad', models.IntegerField(null=True)),
                ('cod_marca', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticulosDimTtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_articulo', models.IntegerField()),
                ('nom_articulo', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=12)),
                ('unidad_venta', models.IntegerField()),
                ('factor_estiba', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inventario_seguridad', models.IntegerField(null=True)),
                ('cod_marca', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriasBodegasDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FactAmacenamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad_entradas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad_salidas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad_ventas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad_devolucion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad_existencias', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad_separacion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad_reserva', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad_transito', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad_no_apta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_registro', models.CharField(max_length=8)),
                ('cod_bodega', models.IntegerField()),
                ('cod_negocio', models.IntegerField()),
                ('cod_linea', models.IntegerField()),
                ('cod_marca', models.IntegerField()),
                ('cod_articulo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LineasDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_linea', models.IntegerField()),
                ('nom_linea', models.CharField(max_length=100)),
                ('cod_negocio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LineasDimTtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_linea', models.IntegerField()),
                ('nom_linea', models.CharField(max_length=100)),
                ('cod_negocio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MarcasDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_marca', models.IntegerField()),
                ('nom_marca', models.CharField(max_length=100)),
                ('cod_linea', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MarcasDimTtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_marca', models.IntegerField()),
                ('nom_marca', models.CharField(max_length=100)),
                ('cod_linea', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NegociosDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_negocio', models.IntegerField()),
                ('nom_negocio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NegociosDimTtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_negocio', models.IntegerField()),
                ('nom_negocio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BodegasDimTtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_bodega', models.CharField(max_length=10)),
                ('nom_bodega', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.CategoriasBodegasDim')),
            ],
        ),
        migrations.CreateModel(
            name='BodegasDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_bodega', models.CharField(max_length=10)),
                ('nom_bodega', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.CategoriasBodegasDim')),
            ],
        ),
    ]
