# Generated by Django 2.2.7 on 2020-08-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteDim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_articulo', models.CharField(max_length=10)),
                ('fecha_fab', models.IntegerField()),
                ('fecha_vencimiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoteDimTtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_articulo', models.CharField(max_length=10)),
                ('fecha_fab', models.IntegerField()),
                ('fecha_vencimiento', models.IntegerField()),
            ],
        ),
    ]
