# Generated by Django 2.2.7 on 2020-08-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200826_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotesdim',
            name='cod_lote',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotesdimttemp',
            name='cod_lote',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
