# Generated by Django 2.2.7 on 2020-08-27 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200826_2210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FactAmacenamiento',
            new_name='FactAlmacenamiento',
        ),
    ]
