# Generated by Django 2.2.7 on 2020-09-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200826_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcasdim',
            name='cod_marca',
            field=models.CharField(max_length=10),
        ),
    ]
