# Generated by Django 2.2.7 on 2020-09-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200910_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcasdimttemp',
            name='cod_marca',
            field=models.CharField(max_length=10),
        ),
    ]
