# Generated by Django 2.2.7 on 2020-09-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200910_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulosdim',
            name='cod_marca',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='articulosdimttemp',
            name='cod_marca',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='factalmacenamiento',
            name='cod_marca',
            field=models.CharField(max_length=10),
        ),
    ]
