# Generated by Django 2.2.7 on 2020-09-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200910_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factalmacenamiento',
            name='cod_bodega',
            field=models.CharField(max_length=10),
        ),
    ]
