# Generated by Django 2.2.7 on 2020-09-13 01:52

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200910_2242'),
        ('core', '0009_auto_20200910_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriasbodegasdim',
            options={'verbose_name': 'Categorías de Bodega'},
        ),
        migrations.AlterField(
            model_name='categoriasbodegasdim',
            name='nom_categoria',
            field=models.CharField(max_length=100, verbose_name='Nombre de Categoría'),
        ),
        migrations.CreateModel(
            name='UploadTemplaCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['csv'])], verbose_name='Archivo Plantilla .csv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Company')),
            ],
        ),
    ]
