# Generated by Django 2.2.7 on 2020-08-27 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_dashboardcedi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Tablero'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentario'},
        ),
    ]
