# Generated by Django 2.2.7 on 2020-09-11 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20200826_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_bodega', models.IntegerField()),
                ('nom_bodega', models.CharField(max_length=100)),
                ('categoria_id', models.IntegerField()),
                ('nom_categoria', models.CharField(max_length=100)),
                ('cod_negocio', models.IntegerField()),
                ('nom_negocio', models.CharField(max_length=100)),
                ('cod_linea', models.IntegerField()),
                ('nom_linea', models.CharField(max_length=100)),
                ('cod_marca', models.IntegerField()),
                ('nom_marca', models.CharField(max_length=100)),
                ('cod_articulo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nom_articulo', models.CharField(max_length=100)),
                ('dias_vencimiento', models.IntegerField()),
                ('sku_devolucion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sku_transito', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sku_no_apta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sku_cantidad_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estibas', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'general_almacenamiento_sku',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(max_length=120, verbose_name='Descripción Tablero'),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre Tablero'),
        ),
        migrations.AlterField(
            model_name='board',
            name='rol',
            field=models.ManyToManyField(related_name='boards', to='account.Rol', verbose_name='Roles permitidos'),
        ),
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analytics.TypeBoard', verbose_name='Tipo de Tablero'),
        ),
        migrations.AlterField(
            model_name='typeboard',
            name='code',
            field=models.IntegerField(verbose_name='Código de tipo tablero'),
        ),
        migrations.AlterField(
            model_name='typeboard',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Tipo tablero'),
        ),
    ]
