# Generated by Django 2.2.7 on 2020-07-01 02:38

from django.db import migrations, models
import django.db.models.deletion
import etl.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20200630_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to=etl.models.user_directory_path)),
                ('min', models.IntegerField(default=1)),
                ('max', models.IntegerField(default=10000)),
                ('separator', models.CharField(default=';', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Company')),
            ],
        ),
    ]
